name: jeeb-bot

services:
  llama-cpp-server:
    image: local/llama.cpp:server-cuda
    volumes:
      - ${PWD}/local-llm-model:/models
    command: 
      - "-m"
      - "/models/${GGUF_MODEL_NAME}"
      - "--port"
      - "8000"
      - "--host"
      - "0.0.0.0"
      - "-n"
      - "1024"
      - "--n-gpu-layers"
      - "12"
      - "--threads"
      - "6"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 2
              capabilities: [gpu]
    healthcheck:
      test: curl --fail http://localhost:8000/health || exit 1
      interval: 1m
      retries: 5
      start_period: 30s
      timeout: 10s
  app:
    depends_on:
      llama-cpp-server:
        condition: service_healthy
